name: bindflow-docs
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pip
  - conda-build
  - ipykernel
  - ipython
  - ipywidgets
  - pip:
    - numpy<2
    - scipy
    - myst-nb
    - myst-parser
    - sphinx_book_theme
    - sphinx==7.2.6
    - sphinx_design
    - sphinxcontrib-katex
    - sphinxcontrib-mermaid
    - sphinx-inline-tabs
    - sphinx_copybutton
    - roman